### ISSUE TITLE
Some problem about the Eigen

### ISSUE THREAD

**Issue by onionysy** [YukunXia/VLOAM-CMU-16833#10]
When I launch the vloam and public the topic to run the bag file, the error appear.
`ysy@ysy-To-be-filled-by-O-E-M:~/catkin/vloam/VLOAM-NOTED-master$ roslaunch vloam_main vloam_main.launch 
... logging to /home/ysy/.ros/log/c999d416-6397-11ec-adfc-200db02d4198/roslaunch-ysy-To-be-filled-by-O-E-M-5684.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ysy-To-be-filled-by-O-E-M:37497/

SUMMARY
========

PARAMETERS
 * /CLAHE: False
 * /detach_VO_LO: True
 * /keypoint_NMS: False
 * /loam_verbose_level: 1
 * /map_pub_number: 20
 * /mapping_line_resolution: 0.4
 * /mapping_plane_resolution: 0.8
 * /mapping_skip_frame: 1
 * /minimum_range: 5.0
 * /optical_flow_match: False
 * /remove_VO_outlier: 100
 * /reset_VO_to_identity: False
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /scan_line: 64
 * /visualize_optical_flow: True
 * /vloam_main_node/publish_point_cloud: True
 * /vloam_main_node/rosbag_rate: 0.33
 * /vloam_main_node/save_traj: True
 * /vloam_main_node/visualize_depth: False

NODES
  /
    rviz (rviz/rviz)
    vloam_main_node (vloam_main/vloam_main_node)

ROS_MASTER_URI=http://localhost:11311

process[vloam_main_node-1]: started with pid [5699]
process[rviz-2]: started with pid [5700]
[ WARN] [1640231903.940193533]: Shutdown request received.
[ WARN] [1640231903.940258711]: Reason given for shutdown: [[/rviz] Reason: new node registered with same name]
[ INFO] [1640231920.634819865]: 
 LO file path; /home/ysy/catkin/vloam/VLOAM-NOTED-master/src/vloam_main/results/2011_09_30_drive_0020/LO1.txt

vloam_main_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
[vloam_main_node-1] process has died [pid 5699, exit code -6, cmd /home/ysy/catkin/vloam/VLOAM-NOTED-master/devel/lib/vloam_main/vloam_main_node __name:=vloam_main_node __log:=/home/ysy/.ros/log/c999d416-6397-11ec-adfc-200db02d4198/vloam_main_node-1.log].
log file: /home/ysy/.ros/log/c999d416-6397-11ec-adfc-200db02d4198/vloam_main_node-1*.log
`
Can you give me some advice how to fix it? Thanks for your reply.

**Comment by onionysy** [comment]
I have locate the problem in
`  vloam_tf = std::make_shared<vloam::VloamTF>();
  VO = std::make_shared<vloam::VisualOdometry>();
  LOAM = std::make_shared<vloam::LidarOdometryMapping>();`
But I don't know how to fix it.

**Comment by YukunXia** [comment]
Hi @onionysy, what's your GCC version? An easy workaround could be upgrading your GCC to have version >= 7, and replacing c++14 with c++17 at the following two lines:
https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/visual_odometry/CMakeLists.txt#L5
https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/lidar_odometry_mapping/CMakeLists.txt#L5

---

Or, as http://eigen.tuxfamily.org/dox-devel/group__TopicStructHavingEigenMembers.html suggests, you could add `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` to classes defined under `src/lidar_odometry_mapping/include/lidar_odometry_mapping` and `src/visual_odometry/include/visual_odometry`, with at least one member variable having its type in the following list

>Eigen::Vector2d
Eigen::Vector4d
Eigen::Vector4f
Eigen::Matrix2d
Eigen::Matrix2f
Eigen::Matrix4d
Eigen::Matrix4f
Eigen::Affine3d
Eigen::Affine3f
Eigen::Quaterniond
Eigen::Quaternionf
(Source: http://eigen.tuxfamily.org/dox-devel/group__TopicFixedSizeVectorizable.html)

In this case, you also need to take care of the `Cause 2: STL Containers or manual memory allocation` on http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html, and search for all problematic variables. For example, `std::vector<Eigen::Vector4f>` exists at this line https://github.com/YukunXia/VLOAM-CMU-16833/blob/50686e356ca268a2310c142fc5aee487f0183d38/src/visual_odometry/src/point_cloud_util.cpp#L317.

---

Overall, I suggest trying out the workaround solution first.
