### ISSUE TITLE
Unable to run rosbag file

### ISSUE THREAD

**Issue by parthmalpathak** [YukunXia/VLOAM-CMU-16833#12]
Hello Yukun,
Thank you for such a great implementation. My team and I have been trying to  implement your repo but are running into the following issue. Could you please guide us in any possible way?

Thank you!

![IMG-1357](https://user-images.githubusercontent.com/65437782/164010138-53f90d77-1357-49e4-8c9b-e18007ead925.jpg)

**Comment by YukunXia** [comment]
Hello Parth, did you `source devel/setup.bash` in this terminal? Another way to confirm that is to press Tab in the terminal to see if the message gets auto-filled.

**Comment by parthmalpathak** [comment]
Thanks for your prompt reply, Yukun. My team and I were able to figure it!
