### ISSUE TITLE
代码中似乎没有提及transform integration

### ISSUE THREAD

**Issue by xiosi** [YukunXia/VLOAM-CMU-16833#14]
vo关了，效果一样？

**Comment by YukunXia** [comment]
https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/lidar_odometry_mapping/src/laser_odometry.cpp#L223-L236

上面这段是VO初始化LO的代码。所有transformation相关的在都存在vloam_tf这个object里。

**Comment by xiosi** [comment]
谢谢您，其实是想看看frame to frame和MO结合的高频率输出是如何实现的，现在看到了。

> https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/lidar_odometry_mapping/src/laser_mapping.cpp#L188-L189

**Comment by YukunXia** [comment]
> 谢谢您，其实是想看看frame to frame和MO结合的高频率输出是如何实现的，现在看到了。
> 
> > https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/lidar_odometry_mapping/src/laser_mapping.cpp#L188-L189

嗯没事，其实这两行是ALOAM写的，然后ALOAM我其实主要是改了下的input output的接口，统一了代码风格。
