### ISSUE TITLE
real time slam

### ISSUE THREAD

**Issue by arashizn** [YukunXia/VLOAM-CMU-16833#16]
hello, after i changed the code to do real slam(haven't calibrate radar and camera),  when i launch the file, the following error occurred, do you have any suggestions? I have no idea about the imu_link, i only find it in .rviz file
 
![image](https://user-images.githubusercontent.com/45659459/174627012-c767b0cf-5864-43d6-bf65-5e6b35f70572.png)

**Comment by arashizn** [comment]
![image](https://user-images.githubusercontent.com/45659459/174629479-d161c385-5d01-43ae-9a4a-5a2d391f453f.png)

**Comment by YukunXia** [comment]
You are at the right place to resolve the issue. 

`VloamTF` handles all transformation information to support odometry, mapping, and visualization. IMU was not used in the project, but I forgot the reason to read transformations related to the `imu_link`. I most likely did that merely to have the code better interact with KITTI. In essence, only https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/vloam_tf/src/vloam_tf.cpp#L56 this line is required to run the program. And for visualization purposes, `base_link`, typically defined on the ground, can be included.

Please feel free to customize the function you posted here, and I hope that works for you.

**Comment by arashizn** [comment]
really thanks, i already solved the problem through deleting part of the code and assigning the matrix new value, it performs well in real time slam!!!

**Comment by arashizn** [comment]
really thanks, i already solved the problem through deleting part of the code and assigning the matrix new value, it performs well in real time slam!!!(except for some jitter)

**Comment by arashizn** [comment]
really thanks, i already solved the problem through deleting part of the code and assigning the matrix new value, it performs well in real time slam!!!(except for some jitter)

**Comment by YukunXia** [comment]
So glad that it works for you!
