### ISSUE TITLE
Error: Tried to advertise a service that is already advertised

### ISSUE THREAD

**Issue by YukunXia** [YukunXia/VLOAM-CMU-16833#5]
Thanks.
when I roslaunch  this, 
process[vloam_main_node -1]: started with pid [18081]
process[rviz-2]: started with pid [18082]
[ERROR] [1626056112.350555675]: Tried to advertise a service that is already advertised in this node [/rviz/compressed/setparameters]
There is nothing when I play the bag.

_Originally posted by @wwq985 in https://github.com/YukunXia/VLOAM-CMU-16833/issues/4#issuecomment-877922595_

@wwq985 Please post all your running steps, and the output screenshots here. Also, please attach your system information, eg. which OS and which version.

**Comment by YukunXia** [comment]
@wwq985 I feel this error may not be problematic? Some top google results guide me to this page: https://answers.ros.org/question/12244/complaint-from-openni_launch-on-already-advertised-services/. And it says you can ignore this error. 

To run the bag, you can't directly use the rosbag syntax, and should follow the instructions here: https://github.com/YukunXia/VLOAM-CMU-16833/tree/master/src/vloam_main

**Comment by KalmanSLAMer** [comment]
yes
It is not a problem.
Thanks .
