### ISSUE TITLE
A question about "demo_lidar"!

### ISSUE THREAD

**Issue by KalmanSLAMer** [YukunXia/VLOAM-CMU-16833#6]
I'm sorry to bother you. l have a problem which I can't run the "demo_lidar" with kitti. Do you know how to run it with the kitti.
I will appreciate if  you can repply to me.

**Comment by YukunXia** [comment]
demo_lidar is a whole different repo... It was written many years ago, and some OpenCV functions seem to be already deprecated. So I'm not surprised if you find it hard to run it. And that was one of the motivations for me to implement VLOAM in the course project. My code should be modern and runnable. The visual odometry part is essentially the "DEMO" and can be run alone without LOAM running.
