### ISSUE TITLE
Unable to obtain the results

### ISSUE THREAD

**Issue by dilaxy123** [YukunXia/VLOAM-CMU-16833#9]
Hi,

I am having a little trouble obtaining the results from this package. I have saved my kitti rosbag files in /VLOAM_ws/src/vloam_main/bags. I ran the command roslaunch vloam_main vloam_main.launch which opens rviz and then in a separate terminal I ran my rosbag files. 

At this point should I see any results in rviz? At the end of the rosbag file  I checked whether any results are saved in /VLOAM_ws/src/vloam_main/results but there were none even though I have made save_traj, true. I am not sure whether I am missing something here.

Any help is much appreciated.

**Comment by YukunXia** [comment]
When `in a separate terminal I ran my rosbag files`, did you use `rosbag play xxx.bag` or `rostopic pub ...`? 

My guess is that you probably used the first one. In that case, you should check the step 3 of https://github.com/YukunXia/VLOAM-CMU-16833/tree/master/src/vloam_main#usage-1. 

If you used the second one as my instruction, did you see the print out message from https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/vloam_main/src/vloam_main_node.cpp#L217? If not, feel free to add some print-out messages for debugging inside this function https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/vloam_main/src/vloam_main_node.cpp#L182

**Comment by dilaxy123** [comment]
It works when I use rostopic pub. Thank you very much

**Comment by yunkong11** [comment]
Hello, do you have any recommended test kitti?Thanks.

**Comment by YukunXia** [comment]
> Hello, do you have any recommended test kitti?Thanks.

Do you mean recommended testing sequences in KITTI?

**Comment by yunkong11** [comment]
I'm sorry, because the internet speed is not good, I often can't board it.
Do you have a testing sequences that can test this algorithm?

**Comment by YukunXia** [comment]
> I'm sorry, because the internet speed is not good, I often can't board it. Do you have a testing sequences that can test this algorithm?

Yes, but only Google Drive link. Does that work for you?  You can also download KITTI dataset and create those bags by yourself, as suggested in the README file

>Step 1, create and move bag files to "REPO_ROOT/src/vloam_main/bags"
> For example: https://github.com/tomas789/kitti2bag

**Comment by yunkong11** [comment]
okay. Thank you, I just started to learn this aspect and I don't understand a lot, thank you for your guidance.
